# This is a basic workflow to help you get started with Actions
# 工作流名称
name: Run CI

# Controls when the workflow will run
# 项目主分支的每次推送时运行工作流
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# 工作流中实际想要发生的事情
jobs:
  # 构建并测试
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 设置 Go 编译器环境  
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.4
      # 从其 GitHub 存储库中查看我们的代码
      - name: Checkout code
        uses: actions/checkout@v2
      # 应用程序使用的 Fetch Go 模块
#       - name: Fetch required Go modules
#         run:  go mod download
      # 为我们的应用程序构建二进制文件
#       - name: Build
#         run:  go build -v ./...
      # 为我们的应用程序构建 Docker 映像
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: ${{ github.event.repository.name }}:latest, ${{ github.repository }}:latest
     # 针对该 Docker 映像运行应用程序的功能测试
#       - name: Run functional tests
#         run:  go test -v ./...
